// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://leplvqapnexpgmivfdpl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxlcGx2cWFwbmV4cGdtaXZmZHBsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczNTg2NjksImV4cCI6MjA3MjkzNDY2OX0.hQMYkofgPxwnfUIX3j7FBzKjDarka8jIHB9XW-QBvTQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});